---
version: '3'
services:
  wpdb:
    container_name: wpdb
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./datadb:/var/lib/mysql
    env_file:
      - wp.env
    networks:
      - internal
      
  wp:
    container_name: wp
    image: wordpress:6.0.0-php8.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    depends_on:
      - wpdb
    env_file:
      - wp.env
    networks:
      - internal
      - web
    expose:
      - "80"
      - "443"
    labels:
      # Caddy
      caddy: ${WP_HOST}
      caddy.reverse_proxy: "{{upstreams http}}"
      # Traefik
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${WP_HOST}"
      traefik.port: '80'

  wpredis:
    container_name: wpredis
    image: redis:6
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - internal
      
networks:
    web:
        external: true
    internal: {}
